# Site settings
title: cokia - Web Developer
description: "A blog about  ubuntu"
baseurl: "/cokia-cinco.github.io"
url: "http://cokia-cinco.github.io"
# but in production: 'https://cokia-cinco.github.io'
# User settings
username: cokia-cinco
user_title: Lorem Ipsum - FrontEnd
email: 23177804@qq.com
twitter_username: cokia
github_username:  cokia-cinco
gplus_username:  cokia
linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: loremipsum
profile_picture: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1577435717595&di=852a5cffaacb4778b8fcd3c0a7a765a5&imgtype=0&src=http%3A%2F%2F00.minipic.eastday.com%2F20170113%2F20170113135525_f5e0c61cde5b59036cb269405594f3fa_1.jpeg
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/cokia-cinco/cokia-cinco.github.io
      new_tab: true
      key_trigger: g
    - title: twitter
      url: /twitter
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: myServer
    url: http://cokia.work/server

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
