# Site settings
title: yoland - Web Developer
description: "A blog about  ubuntu"
baseurl: "/Yoland-svg.github.io"
url: "http://yoland-svg.github.io"
# but in production: 'https://cokia-cinco.github.io'
# User settings
username: yoland-svg
user_title: Lorem Ipsum - FrontEnd
email: 2302046047@qq.com
twitter_username: yoland
github_username:  yoland-svg
gplus_username:  yoland
linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: loremipsum
profile_picture: https://cn.bing.com/images/search?view=detailV2&ccid=bLx51Cqu&id=6AFC07AEA6D29FF1FF1CA2BF98E79BCA0202BECD&thid=OIP.bLx51CquIR2c5rp7BN1GjwHaLI&mediaurl=http%3a%2f%2fpic26.nipic.com%2f20130123%2f4083129_161131324139_2.jpg&exph=1024&expw=681&q=%e5%9b%be%e7%89%87&simid=608008219496939947&ck=12441944FD48769386247862AFD55330&selectedIndex=1&qpvt=%e5%9b%be%e7%89%87&FORM=IRPRST&ajaxhist=0
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/cokia-cinco/cokia-cinco.github.io
      new_tab: true
      key_trigger: g
    - title: twitter
      url: /twitter
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: myServer
    url: http://cokia.work/server

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
